#server
server:
  port: 80
  error:
    whitelabel:
      enabled: false
#spring
spring:
#  mvc:
#    view:
#      prefix: /jsp/
#      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/simplereader?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    template-loader-path: ["/WEB-INF/views/"]
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
